name: sub_screen
description: "A Flutter plugin to support sub screen"
version: 0.1.2
homepage: "https://github.com/hcoderLee/sub_screen_flutter_plugin"

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hcoderlee.subscreen.sub_screen
        pluginClass: SubScreenPlugin